import { Builder } from './settingsLib';
import { StateProp } from './util/state';

export const $FONTS = new Map(java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames().map(v => [v.replace(/\s/g, ''), v]));
$FONTS.set('Mojangles', 'Mojangles');
/** @param {import('./settingsLib').Property<boolean>} prop */
const addDependency = prop => new StateProp(prop).and(prop.shouldShow);

const builder = new Builder('ChickTils', 'settings.json')
  .addPage('General')
  .addToggle('enableGlobal', 'Enable', true, { desc: 'toggles mod globally (scuffed, it doesnt really work)' })
  .addToggle('autoUpdate', 'CheckForUpdates', true, { desc: 'check for updates when loaded' })
  .addToggle('isDev', 'IsDev', false, { desc: 'negatively impacts loading performance and may spam your chat' })
  .addNumber('pingRefreshDelay', 'PingRefreshDelay', 10, { desc: 'how often (in seconds) to refresh ping. set to 0 to disable ping. requires skytils' })
  .addToggle('preferUseTracer', 'PreferUseTracer', true, { desc: 'when available, prefer to use a tracer rather than an arrow' })
  .addOption('textGuiFont', 'TextGuiFont', 'Mojangles', { desc: 'font used for text guis', options: Array.from($FONTS.keys()) })

  .addPage('Kuudra')
  .addToggle('enablekuudra', 'EnableKuudra', true, {})

  .addToggle('kuudraRenderPearlTarget', 'KuudraRenderPearlTarget', true, { desc: 'render location to aim at for sky pearls\n(but not hardcoded + actually accurate + with timer)', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraPearlTargetColor', 'KuudraPearlTargetColor', 0xFFFF00FF, { shouldShow: p => addDependency(p.kuudraRenderPearlTarget), shouldShow: p => addDependency(p.kuudraRenderPearlTarget) })
  .addToggle('kuudraRenderPearlTargetDps', 'KuudraRenderPearlTargetDps', true, { desc: 'target for build -> p4 dps', shouldShow: p => addDependency(p.kuudraRenderPearlTarget) })

  .addToggle('kuudraRenderEmptySupplySpot', 'KuudraRenderEmptySupplySpot', true, { desc: 'render available supply dropoff location', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraEmptySupplySpotColor', 'KuudraEmptySupplySpotColor', 0xFF0000FF, { shouldShow: p => addDependency(p.kuudraRenderEmptySupplySpot) })

  .addToggle('kuudraBoxSupplies', 'KuudraBoxSupplies', true, { shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraBoxSuppliesColor', 'KuudraBoxSuppliesColor', 0x00FF00FF, { shouldShow: p => addDependency(p.kuudraBoxSupplies) })
  .addColor('kuudraBoxSuppliesGiantColor', 'KuudraBoxSuppliesGiantColor', 0, { shouldShow: p => addDependency(p.kuudraBoxSupplies) })
  .addToggle('kuudraBoxSuppliesEsp', 'KuudraBoxSuppliesEsp', true, { shouldShow: p => addDependency(p.kuudraBoxSupplies) })

  .addToggle('kuudraBoxChunks', 'KuudraBoxChunks', true, { shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraBoxChunksColor', 'KuudraBoxChunksColor', 0xFF00FFFF, { shouldShow: p => addDependency(p.kuudraBoxChunks) })
  .addToggle('kuudraBoxChunksEsp', 'KuudraBoxChunksEsp', true, { shouldShow: p => addDependency(p.kuudraBoxChunks) })

  .addToggle('kuudraShowCannonAim', 'KuudraShowCannonAim', true, { desc: 'render location to aim at for cannon, (useful for when client desyncs)', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraCannonAimColor', 'KuudraCannonAimColor', 0xFFFF00FF, { shouldShow: p => addDependency(p.kuudraShowCannonAim) })

  .addToggle('kuudraCustomBossBar', 'KuudraCustomBossBar', true, { desc: 'rescale kuudra health bar in t5 to go 100% -> 0% twice', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })

  .addToggle('kuudraBoxKuudra', 'KuudraBoxKuudra', true, { desc: 'draws box around kuudra', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraBoxKuudraColor', 'KuudraBoxKuudraColor', 0xFF0000FF, { shouldShow: p => addDependency(p.kuudraBoxKuudra) })
  .addToggle('kuudraBoxKuudraEsp', 'KuudraBoxKuudraEsp', true, { shouldShow: p => addDependency(p.kuudraBoxKuudra) })

  .addToggle('kuudraDrawArrowToKuudra', 'KuudraDrawArrowToKuudra', true, { desc: 'draw arrow pointing to kuudra in p5', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addColor('kuudraArrowToKuudraColor', 'KuudraArrowToKuudraColor', 0x00FFFFFF, { shouldShow: p => addDependency(p.kuudraDrawArrowToKuudra) })

  .addToggle('kuudraDrawHpGui', 'KuudraDrawHpOnScreen', true, { desc: 'draw hp of kuudra onto hud', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addAction('moveKuudraHp', 'MoveKuudraHp', null, { shouldShow: p => addDependency(p.kuudraDrawHpGui) })
  .addInteger('kuudraDrawHpDec', 'KuudraDrawHpDecimals', 3, { desc: 'number of decimals/sigfigs in the hp', min: 0, max: 3, shouldShow: p => addDependency(p.kuudraDrawHpGui) })

  .addToggle('kuudraAutoRefillPearls', 'KuudraAutoRefillPearls', true, { desc: 'automatically run /gfs at start of each run to replenish used pearls', shouldShow: p => addDependency(p.enablekuudra), isNewSection: true })
  .addInteger('kuudraAutoRefillPearlsAmount', 'KuudraAutoRefillPearlsAmount', 16, { desc: 'amount of pearls you want to start run with', min: 0, max: 560, shouldShow: p => addDependency(p.kuudraAutoRefillPearls) })

  .addOption('kuudraPickupTitle', 'KuudraPickupTitle', 'Default', { options: ['Default', 'Simplified', 'None'] })

  .addPage('Dungeon')
  .addToggle('enabledungeon', 'EnableDungeon', true, {})

  .addToggle('dungeonBoxMobs', 'DungeonBoxMobs', true, { desc: 'draws boxes around starred mobs\nonly mobs with both nametag and corresponding entity (no ghost nametags!)', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonBoxMobEsp', 'DungeonBoxMobEsp', false, { shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxMobColor', 'DungeonBoxMobColor', 0x00FFFFFF, { desc: 'color for basic mobs', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxKeyColor', 'DungeonBoxKeyColor', 0x00FF00FF, { desc: 'color for wither/blood keys', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxSAColor', 'DungeonBoxSAColor', 0xFF0000FF, { desc: 'color for SAs', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxSMColor', 'DungeonBoxSkeleMasterColor', 0xFF8000FF, { desc: 'color for skele masters', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxFelColor', 'DungeonBoxFelColor', 0x00FF80FF, { desc: 'color for fels', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxChonkColor', 'DungeonBoxChonkersColor', 0xFF0080FF, { desc: 'color for withermancers, commanders, lords, and super archers', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addColor('dungeonBoxMiniColor', 'DungeonBoxMiniColor', 0xB400B4FF, { desc: 'color for LAs,  FAs, and AAs', shouldShow: p => addDependency(p.dungeonBoxMobs) })
  .addToggle('dungeonBoxMobDisableInBoss', 'DungeonBoxMobDisableInBoss', false, { desc: 'pretty much only relevant for SAs in p2', shouldShow: p => addDependency(p.dungeonBoxMobs) })

  .addToggle('dungeonBoxWither', 'DungeonBoxWither', false, { desc: 'boxes wither lords\nindependent from box mobs', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonBoxWitherEsp', 'DungeonBoxWitherEsp', true, { shouldShow: p => addDependency(p.dungeonBoxWither) })
  .addColor('dungeonBoxWitherColor', 'DungeonBoxWitherColor', 0x515A0BFF, { shouldShow: p => addDependency(p.dungeonBoxWither) })

  .addToggle('dungeonBoxLivid', 'DungeonBoxLivid', false, { desc: 'independent from box mobs', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonBoxLividEsp', 'DungeonBoxLividEsp', true, { shouldShow: p => addDependency(p.dungeonBoxLivid) })
  .addColor('dungeonBoxLividColor', 'DungeonBoxLividColor', 0xFF0000FF, { shouldShow: p => addDependency(p.dungeonBoxLivid) })
  .addToggle('dungeonBoxLividDrawArrow', 'DungeonBoxLividDrawArrow', true, { shouldShow: p => addDependency(p.dungeonBoxLivid) })

  .addToggle('dungeonBoxIceSprayed', 'DungeonBoxIceSprayedMobs', false, { desc: 'boxes frozen mobs\nindependent from box mobs', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonBoxIceSprayedEsp', 'DungeonBoxIceSprayedEsp', false, { shouldShow: p => addDependency(p.dungeonBoxIceSprayed) })
  .addColor('dungeonBoxIceSprayedOutlineColor', 'DungeonBoxIceSprayedOutlineColor', 0XADD8E6FF, { shouldShow: p => addDependency(p.dungeonBoxIceSprayed) })
  .addColor('dungeonBoxIceSprayedFillColor', 'DungeonBoxIceSprayedFillColor', 0XADBCE650, { shouldShow: p => addDependency(p.dungeonBoxIceSprayed) })

  .addToggle('dungeonBoxTeammates', 'DungeonBoxTeammates', true, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonBoxTeammatesEsp', 'DungeonBoxTeammatesEsp', true, { shouldShow: p => addDependency(p.dungeonBoxTeammates) })
  .addColor('dungeonBoxTeammatesMageColor', 'DungeonBoxTeammatesMageColor', 0x1793C4FF, { shouldShow: p => addDependency(p.dungeonBoxTeammates) })
  .addColor('dungeonBoxTeammatesArchColor', 'DungeonBoxTeammatesArchColor', 0xE80F0FFF, { shouldShow: p => addDependency(p.dungeonBoxTeammates) })
  .addColor('dungeonBoxTeammatesBersColor', 'DungeonBoxTeammatesBersColor', 0xF77C1BFF, { shouldShow: p => addDependency(p.dungeonBoxTeammates) })
  .addColor('dungeonBoxTeammatesTankColor', 'DungeonBoxTeammatesTankColor', 0x47D147FF, { shouldShow: p => addDependency(p.dungeonBoxTeammates) })
  .addColor('dungeonBoxTeammatesHealColor', 'DungeonBoxTeammatesHealColor', 0xFF00FFFF, { shouldShow: p => addDependency(p.dungeonBoxTeammates) })

  .addToggle('dungeonCamp', 'DungeonEnableCamp', true, { desc: 'blood camp helper', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonCampTimer', 'DungeonCampShowTimer', false, { desc: 'render timer underneath boxes', shouldShow: p => addDependency(p.dungeonCamp) })
  .addColor('dungeonCampWireColor', 'DungeonCampWireColor', 0x00FF00FF, { desc: 'color of wireframe', shouldShow: p => addDependency(p.dungeonCamp) })
  .addColor('dungeonCampBoxColor', 'DungeonCampBoxColor', 0x00FFFFFF, { desc: 'color of shaded box', shouldShow: p => addDependency(p.dungeonCamp) })
  .addToggle('dungeonCampBoxEsp', 'DungeonCampBoxEsp', false, { shouldShow: p => addDependency(p.dungeonCamp) })
  .addInteger('dungeonCampSmoothTime', 'DungeonCampSmoothTime', 500, { desc: 'amount of time in ms spent lerping between different guesses\n(and how often to make guesses)', min: 1, shouldShow: p => addDependency(p.dungeonCamp) })
  .addToggle('dungeonCampSkipTimer', 'DungeonCampDialogueSkipTimer', false, { desc: 'timer until when to kill first 4 blood mobs', shouldShow: p => addDependency(p.dungeonCamp) })
  .addAction('moveDungeonCampSkipTimer', 'MoveDungeonCampSkipTimer', null, { shouldShow: p => addDependency(p.dungeonCampSkipTimer) })

  .addToggle('dungeonHecatombAlert', 'DungeonHecatombAlert', false, { desc: 'alert before end of run to swap to hecatomb (does not work for f4/m4/m7)', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addInteger('dungeonHecatombAlertTime', 'DungeonHecatombAlertTime', 5000, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.dungeonHecatombAlert) })
  .addToggle('dungeonHecatombAlertSound', 'DungeonHecatombAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.dungeonHecatombAlert) })

  .addToggle('dungeonMap', 'DungeonMap', false, { desc: 'does not work yet', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addAction('moveDungeonMap', 'MoveDungeonMap', null, { shouldShow: p => addDependency(p.dungeonMap) })
  .addToggle('dungeonMapHideBoss', 'DungeonMapHideInBoss', false, { shouldShow: p => addDependency(p.dungeonMap) })
  .addToggle('dungeonMapRenderHead', 'DungeonMapRenderPlayerHeads', false, { desc: 'render heads instead of arrows on map', shouldShow: p => addDependency(p.dungeonMap) })
  .addOption('dungeonMapRenderName', 'DungeonMapRenderPlayerNames', 'Holding Leap', { desc: 'render names of players above their marker', options: ['Always', 'Never', 'Holding Leap'], shouldShow: p => addDependency(p.dungeonMap) })
  .addOption('dungeonMapRenderClass', 'DungeonMapRenderPlayerClass', 'Always', { desc: 'render class of players above their marker', options: ['Always', 'Never', 'Holding Leap'], shouldShow: p => addDependency(p.dungeonMap) })
  .addOption('dungeonMapBoxDoors', 'DungeonMapBoxDoors', 'Blood Doors', { desc: 'boxes wither/blood doors', options: ['Always', 'Never', 'Blood Doors'], shouldShow: p => addDependency(p.dungeonMap) })
  .addColor('dungeonMapBoxDoorOutlineColor', 'DungeonMapBoxDoorOutlineColor', 0x00FF00FF, { shouldShow: p => addDependency(p.dungeonMap) })
  .addColor('dungeonMapBoxDoorFillColor', 'DungeonMapBoxDoorFillColor', 0x00FF0050, { shouldShow: p => addDependency(p.dungeonMap) })
  .addColor('dungeonMapBoxLockedDoorOutlineColor', 'DungeonMapBoxLockedDoorOutlineColor', 0xFF0000FF, { shouldShow: p => addDependency(p.dungeonMap) })
  .addColor('dungeonMapBoxLockedDoorFillColor', 'DungeonMapBoxLockedDoorFillColor', 0xFF000050, { shouldShow: p => addDependency(p.dungeonMap) })

  .addOption('dungeonShowSecrets', 'DungeonShowSecrets', 'None', { desc: 'does not work yet, requires map to be on', options: ['None', 'Wire', 'Waypoint'], shouldShow: p => addDependency(p.dungeonMap) })

  .addToggle('dungeonHideHealerPowerups', 'DungeonHideHealerPowerups', true, { desc: 'hide healer power orbs (and particles!)', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonAutoArchitect', 'DungeonAutoGFSArchitect', false, { desc: 'auto gfs on puzzle fail, and a friendly reminder', shouldShow: p => addDependency(p.enabledungeon) })

  .addOption('dungeonNecronDragTimer', 'DungeonNecronDragTimer', 'None', { desc: 'timer when necron does some dragging\n(timer will automatically pop up when instamidding!)', options: ['OnScreen', 'InstaMid', 'Both', 'None'], shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addAction('moveNecronDragTimer', 'MoveNecronDragTimer', null, { shouldShow: p => addDependency(p.dungeonNecronDragTimer) })
  .addInteger('dungeonNecronDragDuration', 'DungeonNecronDragDuration', 120, { desc: 'in ticks, 120 = move/leap, 163 = immunity', min: 0, shouldShow: p => addDependency(p.dungeonNecronDragTimer) })

  .addOption('dungeonDev4Helper', 'DungeonClearViewDev4', 'Both', { desc: 'clearer vision while doing 4th dev', options: ['None', 'Titles', 'Particles', 'Both'], shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonDev4HighlightBlock', 'DungeonDev4HighlightBlock', true, { desc: 'highlights emerald block green, bypasses chunk updates', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addColor('dungeonDev4HighlightBlockColor', 'DungeonDev4HighlightBlockColor', 0x50C878FF, { shouldShow: p => addDependency(p.dungeonDev4HighlightBlock) })
  .addToggle('dungeonDev4HighlightBlockEsp', 'DungeonDev4HighlightBlockEsp', false, { shouldShow: p => addDependency(p.dungeonDev4HighlightBlock) })

  .addToggle('dungeonStairStonkHelper', 'DungeonStairStonkHelper', false, { desc: 'stair stonker stuff', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addColor('dungeonStairStonkHelperColor', 'DungeonStairStonkHelperColor', 0xFF0000FF, { desc: 'draw line to align yourself to dig down a stair\nsame as soopy but does not cut fps in half', shouldShow: p => addDependency(p.dungeonStairStonkHelper) })
  .addColor('dungeonStairStonkHelperHighlightColor', 'DungeonStairStonkHelperHighlightColor', 0x7DF9FF80, { desc: 'highlight stairs this color if they need to be ghosted to stonk', shouldShow: p => addDependency(p.dungeonStairStonkHelper) })

  .addToggle('dungeonAutoRefillPearls', 'DungeonAutoRefillPearls', false, { desc: 'automatically run /gfs to replenish used pearls', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addInteger('dungeonAutoRefillPearlsAmount', 'DungeonAutoRefillPearlsAmount', 16, { desc: 'amount of pearls you want to have at a time', min: 0, max: 560, shouldShow: p => addDependency(p.dungeonAutoRefillPearls) })
  .addInteger('dungeonAutoRefillPearlsThreshold', 'DungeonAutoRefillPearlsThreshold', 0, { desc: 'automatically replenish pearls mid run when below this amount\n0 to disable', min: 0, max: 560, shouldShow: p => addDependency(p.dungeonAutoRefillPearls) })
  .addToggle('dungeonAutoRefillPearlsGhostPickFix', 'DungeonAutoRefillPearlsGhostPickFix', false, { desc: 'dont replenish when ghost pick\n(turn on if you ghost using pearls)', shouldShow: p => new StateProp(p.dungeonAutoRefillPearlsThreshold).notequals(0).and(p.dungeonAutoRefillPearlsThreshold.shouldShow) })

  .addToggle('dungeonM7LBWaypoints', 'DungeonDragonLBWaypoints', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonGoldorDpsStartAlert', 'DungeonGoldorDpsStartAlert', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addInteger('dungeonGoldorDpsStartAlertTime', 'DungeonGoldorDpsStartAlertTime', 500, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.dungeonGoldorDpsStartAlert) })
  .addToggle('dungeonGoldorDpsStartAlertSound', 'DungeonGoldorDpsStartAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.dungeonGoldorDpsStartAlert) })

  .addToggle('dungeonTerminalBreakdown', 'DungeonTerminalBreakdown', false, { desc: 'displays terminals done by each person', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonPlaySoundKey', 'DungeonPlaySoundOnKey', false, { desc: 'play dulkir secret sound on pickup key', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonIceSprayAlert', 'DungeonRareMobDropAlert', true, { desc: 'alert on ice spray/sm cp', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addInteger('dungeonIceSprayAlertTime', 'DungeonRareMobDropAlertTime', 2000, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.dungeonIceSprayAlert) })
  .addToggle('dungeonIceSprayAlertSound', 'DungeonRareMobDropAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.dungeonIceSprayAlert) })

  .addToggle('dungeonTerminalsHelper', 'DungeonTerminalsHelper', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addOption('dungeonTerminalsGuiSize', 'DungeonTerminalsGuiSize', 'Unchanged', { desc: 'change gui size while in terminals', options: ['Unchanged', 'Small', 'Normal', 'Large', '4x', '5x', 'Auto'], shouldShow: p => addDependency(p.dungeonTerminalsHelper) })
  .addToggle('dungeonTerminalsHideInv', 'DungeonTerminalsHideInventory', false, { desc: 'hide inventory in terminals\nplease do not use, it will 1) break all solvers, 2) look shit, 3) probably breaks other things like locking slots', shouldShow: p => addDependency(p.dungeonTerminalsHelper) })
  .addToggle('dungeonTerminalsHideInvScuffed', 'DungeonTerminalsHideInventoryScuffed', false, { desc: 'hide inventory in terminals, but scuffed (basically centers around the chest instead of hiding)', shouldShow: p => addDependency(p.dungeonTerminalsHelper) })

  .addToggle('dungeonSpiritBearHelper', 'DungeonSpiritBearHelper', false, { desc: 'predict spirit bear spawn location', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonSpiritBearTimer', 'DungeonSpiritBearShowTimer', false, { desc: 'render timer above box', shouldShow: p => addDependency(p.dungeonSpiritBearHelper) })
  .addColor('dungeonSpiritBearWireColor', 'DungeonSpiritBearWireColor', 0x00FF00FF, { desc: 'color of wireframe', shouldShow: p => addDependency(p.dungeonSpiritBearHelper) })
  .addColor('dungeonSpiritBearBoxColor', 'DungeonSpiritBearBoxColor', 0x00FFFFFF, { desc: 'color of shaded box', shouldShow: p => addDependency(p.dungeonSpiritBearHelper) })
  .addToggle('dungeonSpiritBearBoxEsp', 'DungeonSpiritBearBoxEsp', false, { shouldShow: p => addDependency(p.dungeonSpiritBearHelper) })
  .addInteger('dungeonSpiritBearSmoothTime', 'DungeonSpiritBearSmoothTime', 500, { desc: 'amount of time in ms spent lerping between different guesses\n(and how often to make guesses)', min: 1, shouldShow: p => addDependency(p.dungeonSpiritBearHelper) })
  .addToggle('dungeonSpiritBearTimerHud', 'DungeonSpiritBearTimerHud', true, { desc: 'show spirit bear timer on hud', shouldShow: p => addDependency(p.dungeonSpiritBearHelper) })
  .addAction('moveSpiritBearTimerHud', 'MoveSpiritBearTimerHud', null, { shouldShow: p => addDependency(p.dungeonSpiritBearTimerHud) })

  .addToggle('dungeonSilverfishHasteTimer', 'DungeonSilverfishHasteTimer', false, { desc: 'render how much longer haste from silverfish will last\nobsolete after haste artifact', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addAction('moveSilverfishHasteTimer', 'MoveSilverfishHasteTimer', null, { shouldShow: p => addDependency(p.dungeonSilverfishHasteTimer) })

  .addToggle('dungeonHideFallingBlocks', 'DungeonHideFallingBlocks', true, { desc: 'dont render falling blocks in boss', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonHideWitherKing', 'DungeonHideWitherKing', true, { desc: 'dont render wither king tentacles', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonDragonHelper', 'DungeonDragonHelper', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addToggle('dungeonDragonHelperTimer2D', 'DungeonDragonHelperTimerHUD', false, { desc: 'render timer until dragon spawn on hud', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addAction('moveDragonHelperTimer', 'MoveDragonHelperTimer', null, { shouldShow: p => addDependency(p.dungeonDragonHelperTimer2D) })
  .addToggle('dungeonDragonHelperTimer3D', 'DungeonDragonHelperTimerWorld', false, { desc: 'render timer until dragon spawn under its chin', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addOption('dungeonDragonHelperAlert', 'DungeonDragonHelperAlert', 'None', { desc: 'show alert when dragon is spawning', options: ['None', 'All', 'Split'], shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addInteger('dungeonDragonHelperAlertTime', 'DungeonDragonHelperAlertTime', 1000, { desc: 'in ms', min: 0, shouldShow: p => new StateProp(p.dungeonDragonHelperAlert).notequals('None').and(p.dungeonDragonHelperAlert.shouldShow) })
  .addToggle('dungeonDragonHelperAlertSound', 'DungeonDragonHelperAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => new StateProp(p.dungeonDragonHelperAlert).notequals('None').and(p.dungeonDragonHelperAlert.shouldShow) })
  .addToggle('dungeonDragonHelperSplit', 'DungeonDragonHelperSplit', true, { desc: 'do you split', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addText('dungeonDragonHelperPrioS', 'DungeonDragonHelperPrioSplit', 'ogrbp', { desc: 'priority to use when splitting\nbers team -> ogrbp <- arch team', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addText('dungeonDragonHelperPrioNS', 'DungeonDragonHelperPrioNoSplit', 'robpg', { desc: 'priority to use when NOT splitting', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addText('dungeonDragonHelperBersTeam', 'DungeonDragonHelperBersTeam', 'bmh', { desc: 'classes that go w/ bers team\nb m h | a t', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addOption('dungeonDragonHelperTrackHits', 'DungeonDragonHelperTrackHits', 'Full', { desc: 'tracks number of arrow hits during drag dps\nnote: will count all arrow hits (will count any hits on husks)\nBurst: count initial "burst" of hits at start of spawn\n(i.e. first 1s if a/b, otherwise time until 5 lbs)\nFull: hits during entire duration dragon is alive\nBoth: full + burst stats', options: ['None', 'Burst', 'Full', 'Both'], shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addOption('dungeonDragonHelperTrackHitsTimeUnit', 'DungeonDragonHelperTrackHitsTimeUnit', 'Both', { desc: 'note: seconds is still measured in ticks, not real time', options: ['Ticks', 'Seconds', 'Both'], shouldShow: p => new StateProp(p.dungeonDragonHelperTrackHits).notequals('None').and(p.dungeonDragonHelperTrackHits.shouldShow) })
  .addToggle('dungeonDragonHelperShowStackAimer', 'DungeonDragonHelperShowStackAimer', false, { desc: 'shows where to aim for stack', shouldShow: p => addDependency(p.dungeonDragonHelper) })
  .addText('dungeonDragonHelperShowStackClass', 'DungeonDragonHelperShowStackClasses', 'ab', { desc: 'what classes to show the aimer as', shouldShow: p => addDependency(p.dungeonDragonHelperShowStackAimer) })
  .addColor('dungeonDragonHelperStackAimerColor', 'DungeonDragonHelperStackAimerColor', 0x00FFFFFF, { shouldShow: p => addDependency(p.dungeonDragonHelperShowStackAimer) })
  .addToggle('dungeonDragonHelperStackAimerPointTo', 'DungeonDragonHelperStackAimerPointTo', true, { desc: 'whether should point to where to aim', shouldShow: p => addDependency(p.dungeonDragonHelperShowStackAimer) })

  .addToggle('dungeonLBPullProgress', 'DungeonLBPullProgress', false, { desc: 'play sounds indicating bow pull progress (accounting for lag)', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addNumber('dungeonLBPullProgressVolume', 'DungeonLBPullProgressVolume', 1, { min: 0, max: 5, shouldShow: p => addDependency(p.dungeonLBPullProgress) })
  .addInteger('dungeonLBPullProgressThreshold', 'DungeonLBPullProgressThreshold', 8, { desc: 'how many ticks to swap to different sound\n0: always, 21: never', min: 0, max: 21, shouldShow: p => addDependency(p.dungeonLBPullProgress) })

  .addToggle('dungeonSimonSays', 'DungeonSimonSays', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addColor('dungeonSimonSaysColor1', 'DungeonSimonSaysColor', 0x00FF00A0, { desc: 'color of the button to press ', shouldShow: p => addDependency(p.dungeonSimonSays) })
  .addColor('dungeonSimonSaysColor2', 'DungeonSimonSaysColorNext', 0xFFFF00A0, { desc: 'color of the next button to press', shouldShow: p => addDependency(p.dungeonSimonSays) })
  .addColor('dungeonSimonSaysColor3', 'DungeonSimonSaysColorOther', 0xFF0000A0, { desc: 'color of the other buttons', shouldShow: p => addDependency(p.dungeonSimonSays) })
  .addOption('dungeonSimonSaysBlock', 'DungeonSimonSaysBlockClicks', 'ExceptWhenCrouching', { desc: 'block incorrect clicks', options: ['Never', 'Always', 'WhenCrouching', 'ExceptWhenCrouching'], shouldShow: p => addDependency(p.dungeonSimonSays) })

  .addToggle('dungeonArrowAlign', 'DungeonArrowAlign', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addOption('dungeonArrowAlignBlock', 'DungeonArrowAlignBlockClicks', 'ExceptWhenCrouching', { desc: 'block incorrect clicks', options: ['Never', 'Always', 'WhenCrouching', 'ExceptWhenCrouching'], shouldShow: p => addDependency(p.dungeonArrowAlign) })
  .addToggle('dungeonArrowAlignLeavePD', 'DungeonArrowAlignLeaveOnePD', true, { desc: 'leave 1 frame at 1 click away during pd', shouldShow: p => addDependency(p.dungeonArrowAlign) })

  .addToggle('dungeonGoldorFrenzyTimer', 'DungeonGoldorFrenzyTimer', false, { desc: 'show timer until next goldor frenzy tick', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addAction('moveGoldorFrenzyTimer', 'MoveGoldorFrenzyTimer', null, { shouldShow: p => addDependency(p.dungeonGoldorFrenzyTimer) })

  .addNumber('dungeonBlockOverlaySize', 'DungeonBlockOverlaySize', 1, { desc: 'size of overlay when inside an opaque block\nin range [0, 1], 0 = none, 1 = default', min: 0, max: 1, shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addOption('dungeonHideHealerFairy', 'DungeonHideHealerFairy', 'Own', { options: ['Never', 'Own', 'Always'], shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonDHubHighlightLow', 'DungeonDHubSelectorHighlight', true, { desc: 'green for low players :)', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonTerracottaRespawn', 'DungeonTerracottaRespawnTimer', false, { shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })
  .addOption('dungeonTerracottaRespawnType', 'DungeonTerracottaRespawnTimerType', 'Timer', { options: ['Timer', 'Box', 'Both'], shouldShow: p => addDependency(p.dungeonTerracottaRespawn) })
  .addColor('dungeonTerracottaRespawnOutlineColor', 'DungeonTerracottaRespawnOutlineColor', 0x91553DFF, { shouldShow: p => new StateProp(p.dungeonTerracottaRespawnType).notequals('Timer').and(p.dungeonTerracottaRespawnType.shouldShow) })
  .addColor('dungeonTerracottaRespawnFillColor', 'DungeonTerracottaRespawnFillColor', 0xA27157A0, { shouldShow: p => new StateProp(p.dungeonTerracottaRespawnType).notequals('Timer').and(p.dungeonTerracottaRespawnType.shouldShow) })
  .addToggle('dungeonTerracottaRespawnGui', 'DungeonTerracottaRespawnGui', false, { desc: 'render the timer for the first terracotta on hud', shouldShow: p => addDependency(p.dungeonTerracottaRespawn) })
  .addAction('moveDungeonTerracottaRespawnGui', 'MoveDungeonTerracottaRespawnGui', null, { shouldShow: p => addDependency(p.dungeonTerracottaRespawnGui) })

  .addToggle('dungeonStormClearLaser', 'DungeonStormClearLaserChecker', false, { desc: 'warn when someone is using laser in storm clear', shouldShow: p => addDependency(p.enabledungeon), isNewSection: true })

  .addToggle('dungeonHideSoulweaverSkulls', 'DungeonHideSoulweaverSkulls', true, { shouldShow: p => addDependency(p.enabledungeon) })

  .addToggle('dungeonGuessMimic', 'DungeonGuessMimic', true, { desc: 'requires skytils\nattempts to guess state of mimic + prince', shouldShow: p => addDependency(p.enabledungeon) })

  .addToggle('dungeonPrinceKilledMessage', 'DungeonPrinceKilled', true, { desc: 'send message on prince death', shouldShow: p => addDependency(p.enabledungeon) })

  .addPage('Stat Gui')
  .addToggle('enablestatgui', 'EnableStatGUI', false, { desc: 'render stats from tab onto hud' })
  .addToggle('loc0', 'EnablePrivateIslandGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc0', 'MovePrivateIslandGUI', null, { shouldShow: p => addDependency(p.loc0) })
  .addToggle('loc1', 'EnableHubGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc1', 'MoveHubGUI', null, { shouldShow: p => addDependency(p.loc1) })
  .addToggle('loc2', 'EnableDungeonHubGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc2', 'MoveDungeonHubGUI', null, { shouldShow: p => addDependency(p.loc2) })
  .addToggle('loc3', 'EnableTheFarmingIslandsGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc3', 'MoveTheFarmingIslandsGUI', null, { shouldShow: p => addDependency(p.loc3) })
  .addToggle('loc4', 'EnableGardenGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc4', 'MoveGardenGUI', null, { shouldShow: p => addDependency(p.loc4) })
  .addToggle('loc5', 'EnableTheParkGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc5', 'MoveTheParkGUI', null, { shouldShow: p => addDependency(p.loc5) })
  .addToggle('loc6', 'EnableGoldMineGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc6', 'MoveGoldMineGUI', null, { shouldShow: p => addDependency(p.loc6) })
  .addToggle('loc7', 'EnableDeepCavernsGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc7', 'MoveDeepCavernsGUI', null, { shouldShow: p => addDependency(p.loc7) })
  .addToggle('loc8', 'EnableDwarvenMinesGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc8', 'MoveDwarvenMinesGUI', null, { shouldShow: p => addDependency(p.loc8) })
  .addToggle('loc9', 'EnableCrystalHollowsGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc9', 'MoveCrystalHollowsGUI', null, { shouldShow: p => addDependency(p.loc9) })
  .addToggle('loc10', 'EnableSpidersDenGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc10', 'MoveSpidersDenGUI', null, { shouldShow: p => addDependency(p.loc10) })
  .addToggle('loc11', 'EnableTheEndGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc11', 'MoveTheEndGUI', null, { shouldShow: p => addDependency(p.loc11) })
  .addToggle('loc12', 'EnableCrimsonIsleGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc12', 'MoveCrimsonIsleGUI', null, { shouldShow: p => addDependency(p.loc12) })
  .addToggle('loc13', 'EnableKuudraGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc13', 'MoveKuudraGUI', null, { shouldShow: p => addDependency(p.loc13) })
  .addToggle('loc14', 'EnableTheRiftGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc14', 'MoveTheRiftGUI', null, { shouldShow: p => addDependency(p.loc14) })
  .addToggle('loc15', 'EnableJerrysWorkshopGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc15', 'MoveJerrysWorkshopGUI', null, { shouldShow: p => addDependency(p.loc15) })
  .addToggle('loc16', 'EnableCatacombsGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc16', 'MoveCatacombsGUI', null, { shouldShow: p => addDependency(p.loc16) })
  .addToggle('loc17', 'EnableBackwaterBayouGUI', true, { shouldShow: p => addDependency(p.enablestatgui) })
  .addAction('moveLoc17', 'MoveBackwaterBayouGUI', null, { shouldShow: p => addDependency(p.loc17) })

  .addPage('Server Tracker')
  .addToggle('enableservertracker', 'EnableServerTracker', true, { desc: 'tracks servers you\'ve been to, also /warp tab complete' })
  .addInteger('serverTrackerTransferCd', 'ServerTrackerTransferCd', 3000, { desc: 'delays warps by this long if spammed too quickly', min: 0, shouldShow: p => addDependency(p.enableservertracker) })
  .addText('serverTrackerCdMessage', 'ServerTrackerCdMessage', 'waiting for cd (u.U)｡｡｡ zzZ', { shouldShow: p => addDependency(p.enableservertracker) })

  .addPage('RatTils')
  .addToggle('enablerattils', 'EnableRatTils', true, { desc: 'boxes cheese and other stuff' })
  .addColor('ratTilsBoxColor', 'RatTilsBoxColor', 0x00FF80FF, { shouldShow: p => addDependency(p.enablerattils), isNewSection: true })
  .addToggle('ratTilsBoxEsp', 'RatTilsBoxEsp', true, { shouldShow: p => addDependency(p.enablerattils) })
  .addInteger('ratTilsAlertTime', 'RatTilsAlertTime', 2000, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.enablerattils), isNewSection: true })
  .addToggle('ratTilsAlertSound', 'RatTilsAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.enablerattils) })
  .addText('ratTilsMessage', 'RatTilsMessage', 'i.imgur.com/8da4IiM.png', { desc: 'empty to disable', shouldShow: p => addDependency(p.enablerattils), isNewSection: true })
  .addText('ratTilsChannel', 'RatTilsChannel', 'pc', { shouldShow: p => new StateProp(p.ratTilsMessage).notequals('').and(p.ratTilsMessage.shouldShow) })
  .addToggle('ratTilsMuteSound', 'RatTilsMuteSound', true, { desc: 'mute rat squeaking sounds', shouldShow: p => addDependency(p.enablerattils), isNewSection: true })

  .addPage('Powder Chest')
  .addToggle('enablepowderalert', 'EnablePowderAlert', false, { desc: 'alerts when powder chest spawns' })
  .addInteger('powderScanRange', 'PowderScanRange', 10, { min: 0, shouldShow: p => addDependency(p.enablepowderalert), isNewSection: true })
  .addToggle('powderBoxEsp', 'PowderBoxEsp', true, { shouldShow: p => addDependency(p.enablepowderalert), isNewSection: true })
  .addColor('powderBoxColor', 'PowderBoxColor', 0x00FFFFA0, { shouldShow: p => addDependency(p.enablepowderalert) })
  .addColor('powderBoxColor2', 'PowderBoxColorDead', 0xFF0000FF, { desc: '2nd color of gradient  between 1st and 2nd based on when chest will despawn', shouldShow: p => addDependency(p.enablepowderalert) })
  .addInteger('powderAlertTime', 'PowderAlertTime', 1000, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.enablepowderalert), isNewSection: true })
  .addToggle('powderAlertSound', 'PowderAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.enablepowderalert) })
  .addToggle('powderBlockRewards', 'PowderHideMessage', true, { desc: 'hides chest rewards message', shouldShow: p => addDependency(p.enablepowderalert), isNewSection: true })
  .addToggle('powderShowPowder', 'PowderHideMessageShowPowder', true, { desc: 'keep the powder gain message', shouldShow: p => addDependency(p.powderBlockRewards) })

  .addPage('Crystal Alert')
  .addToggle('enablecrystalalert', 'EnableCrystalAlert', false, { desc: 'alerts when end crystals spawn' })
  .addColor('crystalBoxColor', 'CrystalBoxColor', 0x00FF00FF, { shouldShow: p => addDependency(p.enablecrystalalert) })
  .addToggle('crystalBoxEsp', 'CrystalBoxEsp', true, { shouldShow: p => addDependency(p.enablecrystalalert) })
  .addInteger('crystalAlertTime', 'CrystalAlertTime', 1000, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.enablecrystalalert) })
  .addToggle('crystalAlertSound', 'CrystalAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.enablecrystalalert) })

  .addPage('Command Aliases')
  .addToggle('enablecmdalias', 'EnableCommandAliases', true, {})
  .addToggle('cmdAliasStorage', 'EnableStorageShortcut', true, { desc: 'e.g. /b1, /e2, and /3 for /backpack 1, /enderchest 2, /backpack 3 respectively', shouldShow: p => addDependency(p.enablecmdalias) })
  .addToggle('cmdAliasDungeon', 'EnableDungeonShortcut', true, { desc: 'e.g. /f1, /m1, /fe', shouldShow: p => addDependency(p.enablecmdalias) })
  .addToggle('cmdAliasKuudra', 'EnableKuudraShortcut', true, { desc: 'e.g. /k1', shouldShow: p => addDependency(p.enablecmdalias) })

  .addPage('Quiver Display')
  .addToggle('enablequiver', 'EnableQuiverDisplay', false, { desc: 'arrow display on hud, only works when holding bow' })
  .addAction('moveQuiver', 'MoveQuiverDisplay', null, { shouldShow: p => addDependency(p.enablequiver) })
  .addOption('quiverSize', 'QuiverMaxSize', 'Giant', { desc: 'size of quiver (based on feather collection)', options: ['Medium', 'Large', 'Giant'], shouldShow: p => addDependency(p.enablequiver) })
  .addToggle('quiverShowRefill', 'QuiverShowRefillCost', false, { desc: 'show refill cost', shouldShow: p => addDependency(p.enablequiver) })
  .addOption('quiverRefillCost', 'QuiverRefillCostType', 'Instant', { desc: 'method of refilling\nInstant: whatever is fastest\nIndividual: spam left click at jax (cheaper, also ur a loser)\nJax: same as instant but jax flint arrows expensiver\nOphelia: same as instant', options: ['Instant', 'Individual', 'Jax', 'Ophelia'], shouldShow: p => addDependency(p.quiverShowRefill) })
  .addPercent('quiverShowRefillThresh', 'QuiverRefillCostDisplayThreshold', 25, { desc: 'only show refill cost when below this amount full', min: 0, max: 100, shouldShow: p => addDependency(p.quiverShowRefill) })

  .addPage('Rabbit')
  .addToggle('enablerabbit', 'EnableRabbitTils', false, {})
  .addToggle('rabbitShowBestUpgrade', 'RabbitTilsShowBestUpgrade', true, { desc: 'highlight most cost effective rabbit upgrade', shouldShow: p => addDependency(p.enablerabbit) })
  .addToggle('rabbitCondenseChat', 'RabbitTilsCondenseChat', true, { desc: 'has been promoted lookin mf', shouldShow: p => addDependency(p.enablerabbit) })

  .addPage('ChatTils')
  .addToggle('enablechattils', 'EnableChatTils', false, {})

  .addToggle('chatTilsWaypoint', 'ChatTilsFindWaypoints', true, { desc: 'look for waypoints in all the chats', shouldShow: p => addDependency(p.enablechattils), isNewSection: true })
  .addOption('chatTilsWaypointType', 'ChatTilsWaypointType', 'Box', { desc: 'type of waypoint', options: ['Box', 'Wireframe', 'None'], shouldShow: p => addDependency(p.chatTilsWaypoint) })
  .addColor('chatTilsWaypointColor', 'ChatTilsWaypointColor', 0xC80000FF, { shouldShow: p => addDependency(p.chatTilsWaypoint) })
  .addToggle('chatTilsWaypointBeacon', 'ChatTilsWaypointShowBeacon', true, { desc: 'render beacon to waypoint', shouldShow: p => addDependency(p.chatTilsWaypoint) })
  .addToggle('chatTilsWaypointName', 'ChatTilsWaypointShowName', false, { desc: 'show name of player who sent waypoint', shouldShow: p => addDependency(p.chatTilsWaypoint) })
  .addInteger('chatTilsWaypointDuration', 'ChatTilsWaypointDuration', 60, { desc: 'time in seconds, 0 = forever', min: 0, shouldShow: p => addDependency(p.chatTilsWaypoint) })
  .addToggle('chatTilsWaypointShowOwn', 'ChatTilsWaypointShowOwn', true, { desc: 'show your own waypoints', shouldShow: p => addDependency(p.chatTilsWaypoint) })
  .addToggle('chatTilsWaypointPersist', 'ChatTilsWaypointPersist', false, { desc: 'whether to persist on swapping servers', shouldShow: p => addDependency(p.chatTilsWaypoint) })

  .addOption('chatTilsHideBonzo', 'ChatTilsHidePartyChatBonzo', 'False', { desc: '"Bonzo Procced (3s)" ("Both" hides chat + sound)', options: ['False', 'Sound', 'Both'], shouldShow: p => addDependency(p.enablechattils), isNewSection: true })
  .addOption('chatTilsHidePhoenix', 'ChatTilsHidePartyChatPhoenix', 'False', { desc: '"Phoenix Procced (3s)" ("Both" hides chat + sound)', options: ['False', 'Sound', 'Both'], shouldShow: p => addDependency(p.enablechattils) })
  .addOption('chatTilsHideSpirit', 'ChatTilsHidePartyChatSpirit', 'False', { desc: '"Spirit Procced (3s)" ("Both" hides chat + sound)', options: ['False', 'Sound', 'Both'], shouldShow: p => addDependency(p.enablechattils) })
  .addOption('chatTilsHideLeap', 'ChatTilsHidePartyChatLeaps', 'False', { desc: '"Leaped/Leaping to plinkingndriving" ("Both" hides chat + sound)', options: ['False', 'Sound', 'Both'], shouldShow: p => addDependency(p.enablechattils) })
  .addOption('chatTilsHideMelody', 'ChatTilsHidePartyChatMelody', 'False', { desc: '"melody (1/4)/25%" ("Both" hides chat + sound)', options: ['False', 'Sound', 'Both'], shouldShow: p => addDependency(p.enablechattils) })
  .addToggle('chatTilsCompactMelody', 'ChatTilsCompactPartyChatMelody', true, { desc: 'only keep most recent melody message from a player', shouldShow: p => addDependency(p.enablechattils) })

  .addToggle('chatTilsClickAnywhereFollow', 'ChatTilsClickAnywhereFollow', false, { desc: 'click anywhere after opening chat to follow party member\n(mostly for diana/assfang/jumpy dt cube)', shouldShow: p => addDependency(p.enablechattils), isNewSection: true })
  .addToggle('chatTilsClickAnywhereFollowOnlyLead', 'ChatTilsClickAnywhereFollowOnlyLead', true, { desc: 'only follow leader', shouldShow: p => addDependency(p.chatTilsClickAnywhereFollow) })

  .addToggle('chatTilsImageArt', 'ChatTilsImageArt', false, { desc: 'generate ascii art from image\nusage: /printimage [image url]\n/printimage (will print image from clipboard)\n/printimage https://i.imgur.com/things.jpeg (will print image from url)', shouldShow: p => addDependency(p.enablechattils), isNewSection: true })
  .addToggle('chatTilsImageArtParty', 'ChatTilsImageArtPartyChat', true, { desc: 'always send in party chat', shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addToggle('chatTilsImageArtAutoPrint', 'ChatTilsImageArtAutoPrint', false, { desc: 'auto print all lines of the image', shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addInteger('chatTilsImageArtWidth', 'ChatTilsImageArtPartyWidth', 40, { desc: 'width of the generated image (in characters)\nheight automatically scaled', min: 1, max: 128, shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addOption('chatTilsImageArtEncoding', 'ChatTilsImageArtEncoding', 'Braille', { desc: 'encoding used', options: ['Braille', 'ASCII'], shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addToggle('chatTilsImageArtUseGaussian', 'ChatTilsImageArtSmooth', false, { desc: 'apply a gaussian blur to image before processing (best results when sobel is used)', shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addToggle('chatTilsImageArtSharpen', 'ChatTilsImageArtSharpen', true, { desc: 'sharpen source image', shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addToggle('chatTilsImageArtDither', 'ChatTilsImageArtDither', true, { desc: 'apply dithering', shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addToggle('chatTilsImageArtInvert', 'ChatTilsImageArtInvert', true, { desc: 'invert colors', shouldShow: p => addDependency(p.chatTilsImageArt) })
  .addOption('chatTilsImageArtAlgorithm', 'ChatTilsImageArtAlgorithm', 'Grayscale', { desc: 'transform algorithm used', options: ['Grayscale', 'Sobel'], shouldShow: p => addDependency(p.chatTilsImageArt) })

  .addToggle('chatTilsEssential', 'ChatTilsBetterEssential', false, { desc: 'show Essential messages in mc chat\n/we, /te, /re, and /fe for corresponding Essential actions', shouldShow: p => addDependency(p.enablechattils), isNewSection: true })
  .addToggle('chatTilsEssentialPing', 'ChatTilsEssentialPing', true, { desc: 'send chat pings on recieve message', shouldShow: p => addDependency(p.chatTilsEssential) })
  .addToggle('chatTilsEssentialNotif', 'ChatTilsEssentialNotification', false, { desc: 'send Essential notification on recieve message', shouldShow: p => addDependency(p.chatTilsEssential) })
  .addToggle('chatTilsEssentialOverrideCommands', 'ChatTilsBetterEssentialOverrideCommands', false, { desc: 'override the /w, /t, /r, and /f commands to be Essential ones', shouldShow: p => addDependency(p.chatTilsEssential) })
  .addToggle('chatTilsEssentialForwardPartyDms', 'ChatTilsEssentialForwardPartyDms', false, { desc: 'any essential dms from party members will be forwarded to party chat', shouldShow: p => addDependency(p.chatTilsEssential) })
  .addToggle('chatTilsEssentialRedirectPartyChat', 'ChatTilsEssentialRedirectPartyChat', false, { desc: 'redirect /pc to message leader on essentials\nalso enables /chat p and /chat party', shouldShow: p => addDependency(p.chatTilsEssential) })

  .addPage('Diana')
  .addToggle('enablediana', 'EnableDiana', false, {})
  .addToggle('dianaArrowToBurrow', 'DianaArrowToBurrow', true, { desc: 'draw an arrow pointing to nearest burrow', shouldShow: p => addDependency(p.enablediana), isNewSection: true })
  .addColor('dianaArrowToBurrowColor', 'DianaArrowToBurrowColor', 0x9FE2BF, { shouldShow: p => addDependency(p.dianaArrowToBurrow) })
  .addToggle('dianaScanBurrows', 'DianaScanBurrows', true, { desc: 'look for burrows by particles', shouldShow: p => addDependency(p.enablediana), isNewSection: true })
  .addColor('dianaBurrowStartColor', 'DianaBurrowStartColor', 0xBBEEEEFF, { shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addColor('dianaBurrowMobColor', 'DianaBurrowMobColor', 0x2A1D32FF, { shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addColor('dianaBurrowTreasureColor', 'DianaBurrowTreasureColor', 0xFED02AFF, { shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addToggle('dianaAlertFoundBurrow', 'DianaAlertFoundBurrow', true, { desc: 'alert when burrow is found', shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addToggle('dianaAlertFoundBurrowNoStart', 'DianaAlertFoundBurrowNoStart', false, { desc: 'do not alert when found burrow is a start burrow', shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addInteger('dianaAlertFoundBurrowTime', 'DianaAlertFoundBurrowTime', 500, { desc: 'in ms', shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addToggle('dianaAlertFoundBurrowSound', 'DianaAlertFoundBurrowSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.dianaScanBurrows) })
  .addToggle('dianaGuessFromParticles', 'DianaGuessFromParticles', false, { desc: '/togglesound must be on', shouldShow: p => addDependency(p.enablediana), isNewSection: true })
  .addToggle('dianaGuessRememberPrevious', 'DianaRememberPreviousGuesses', true, { desc: 'guesses only removed when nearby burrow is found i.e. DianaScanBurrows must be on\nor use /ctsremoveclosestdiana', shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addColor('dianaBurrowPrevGuessColor', 'DianaBurrowPrevGuessColor', 0x707020FF, { shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addColor('dianaGuessFromParticlesPathColor', 'DianaGuessFromParticlesPathColor', 0x00FFFFFF, { desc: 'color of path of particles', shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addToggle('dianaGuessFromParticlesRenderName', 'DianaGuessFromParticlesRenderName', false, { shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addColor('dianaGuessFromParticlesAverageColor', 'DianaGuessFromParticlesAverageColor', 0xB000B5FF, { desc: 'color of geometric median of all guesses', shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addColor('dianaGuessFromParticlesSplineColor', 'DianaGuessFromParticlesSplineColor', 0x138686FF, { desc: 'color of guess from spline estimation', shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addColor('dianaGuessFromParticlesMLATColor', 'DianaGuessFromParticlesMLATColor', 0xB31919FF, { desc: 'color of guess from multilateration', shouldShow: p => addDependency(p.dianaGuessFromParticles) })
  .addColor('dianaGuessFromParticlesBezierColor', 'DianaGuessFromParticlesBezierColor', 0xFF8000FF, { desc: 'color of guess from bezier + control point', shouldShow: p => addDependency(p.dianaGuessFromParticles) })

  .addPage('HUD')
  .addToggle('enableabsorption', 'EnableCustomAbsorption', false, { desc: 'custom absorption renderer to more accurately portray total hp' })
  .addInteger('absorptionMaxHearts', 'AbsorptionMaxHearts', 40, { desc: 'caps hearts for things like mastiff', min: 0, shouldShow: p => addDependency(p.enableabsorption) })

  .addToggle('enableserverscrutinizer', 'EnableServerScrutinizer', false, { desc: 'scrutinizes the server\'s tps and things', isNewSection: true })

  .addToggle('serverScrutinizerTPSDisplay', 'ServerScrutinizerTPSDisplay', true, { desc: 'tracks tps', shouldShow: p => addDependency(p.enableserverscrutinizer), isNewSection: true })
  .addAction('moveTPSDisplay', 'MoveTPSDisplay', null, { shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addInteger('serverScrutinizerTPSDisplayFpsCap', 'ServerScrutinizerTPSDisplayFpsCap', 4, { desc: '0 for uncapped', min: 0, shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addToggle('serverScrutinizerTPSDisplayCap20', 'ServerScrutinizerCapTPS', false, { desc: 'caps all tps at 20', shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addToggle('serverScrutinizerTPSDisplayCurr', 'ServerScrutinizerDisplayCurrentTPS', false, { desc: 'show current tps', shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addToggle('serverScrutinizerTPSDisplayAvg', 'ServerScrutinizerDisplayAverageTPS', true, { desc: 'show average tps', shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addToggle('serverScrutinizerTPSDisplayMin', 'ServerScrutinizerDisplayMinimumTPS', false, { desc: 'show minimum tps', shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addToggle('serverScrutinizerTPSDisplayMax', 'ServerScrutinizerDisplayMaximumTPS', false, { desc: 'show maximum tps', shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })
  .addInteger('serverScrutinizerTPSMaxAge', 'ServerScrutinizerTPSMaxAge', 5000, { desc: 'max age of ticks', min: 1000, shouldShow: p => addDependency(p.serverScrutinizerTPSDisplay) })

  .addToggle('serverScrutinizerLastTickDisplay', 'ServerScrutinizerLastPacketDisplay', true, { desc: 'tracks last packet sent time (lag spike)', shouldShow: p => addDependency(p.enableserverscrutinizer), isNewSection: true })
  .addAction('moveLastTickDisplay', 'MoveLastTickDisplay', null, { shouldShow: p => addDependency(p.serverScrutinizerLastTickDisplay) })
  .addInteger('serverScrutinizerLastTickThreshold', 'ServerScrutinizerLastPacketThreshold', 200, { desc: 'only show when server has not responded for this amount of time\nin ms', shouldShow: p => addDependency(p.serverScrutinizerLastTickDisplay) })

  .addToggle('serverScrutinizerFPSDisplay', 'ServerScrutinizerFPSDisplay', false, { desc: 'tracks FPS', shouldShow: p => addDependency(p.enableserverscrutinizer), isNewSection: true })
  .addAction('moveFPSDisplay', 'MoveFPSDisplay', null, { shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })
  .addInteger('serverScrutinizerFPSDisplayFpsCap', 'ServerScrutinizerFPSDisplayFpsCap', 10, { desc: '0 for uncapped', min: 0, shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })
  .addToggle('serverScrutinizerFPSDisplayCurr', 'ServerScrutinizerDisplayCurrentFPS', true, { desc: 'show current fps', shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })
  .addToggle('serverScrutinizerFPSDisplayAvg', 'ServerScrutinizerDisplayAverageFPS', true, { desc: 'show average fps', shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })
  .addToggle('serverScrutinizerFPSDisplayMin', 'ServerScrutinizerDisplayMinimumFPS', true, { desc: 'show minimum fps', shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })
  .addToggle('serverScrutinizerFPSDisplayMax', 'ServerScrutinizerDisplayMaximumFPS', true, { desc: 'show maximum fps', shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })
  .addInteger('serverScrutinizerFPSMaxAge', 'ServerScrutinizerFPSMaxAge', 5000, { desc: 'max age of ticks', min: 1000, shouldShow: p => addDependency(p.serverScrutinizerFPSDisplay) })

  .addToggle('serverScrutinizerPingDisplay', 'ServerScrutinizerPingDisplay', false, { desc: 'tracks ping', shouldShow: p => addDependency(p.enableserverscrutinizer), isNewSection: true })
  .addAction('movePingDisplay', 'MovePingDisplay', null, { shouldShow: p => addDependency(p.serverScrutinizerPingDisplay) })
  .addInteger('serverScrutinizerPingDisplayFpsCap', 'ServerScrutinizerPingDisplayFpsCap', 4, { desc: '0 for uncapped', min: 0, shouldShow: p => addDependency(p.serverScrutinizerPingDisplay) })
  .addToggle('serverScrutinizerPingDisplayCurr', 'ServerScrutinizerDisplayCurrentPing', true, { desc: 'show current ping', shouldShow: p => addDependency(p.serverScrutinizerPingDisplay) })
  .addToggle('serverScrutinizerPingDisplayAvg', 'ServerScrutinizerDisplayAveragePing', true, { desc: 'show average ping', shouldShow: p => addDependency(p.serverScrutinizerPingDisplay) })
  .addToggle('serverScrutinizerPingDisplayMedian', 'ServerScrutinizerDisplayMedianPing', true, { desc: 'show median ping', shouldShow: p => addDependency(p.serverScrutinizerPingDisplay) })

  .addToggle('serverScrutinizerPPSDisplay', 'ServerScrutinizerPPSDisplay', false, { desc: 'tracks PPS (packets [send] per second)', shouldShow: p => addDependency(p.enableserverscrutinizer), isNewSection: true })
  .addAction('movePPSDisplay', 'MovePPSDisplay', null, { shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })
  .addInteger('serverScrutinizerPPSDisplayFpsCap', 'ServerScrutinizerPPSDisplayFpsCap', 5, { desc: '0 for uncapped', min: 0, shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })
  .addToggle('serverScrutinizerPPSDisplayCurr', 'ServerScrutinizerDisplayCurrentPPS', true, { desc: 'show current pps', shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })
  .addToggle('serverScrutinizerPPSDisplayAvg', 'ServerScrutinizerDisplayAveragePPS', true, { desc: 'show average pps', shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })
  .addToggle('serverScrutinizerPPSDisplayMin', 'ServerScrutinizerDisplayMinimumPPS', true, { desc: 'show minimum pps', shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })
  .addToggle('serverScrutinizerPPSDisplayMax', 'ServerScrutinizerDisplayMaximumPPS', true, { desc: 'show maximum pps', shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })
  .addInteger('serverScrutinizerPPSMaxAge', 'ServerScrutinizerPPSMaxAge', 5000, { desc: 'max age of ticks', min: 1000, shouldShow: p => addDependency(p.serverScrutinizerPPSDisplay) })

  .addToggle('enablespotify', 'EnableSpotifyDisplay', false, { desc: 'shows current song playing on spotify, only works on windows + app version', isNewSection: true })
  .addAction('moveSpotifyDisplay', 'MoveSpotifyDisplay', null, { shouldShow: p => addDependency(p.enablespotify) })
  .addToggle('spotifyHideNotOpen', 'SpotifyHideIfNotOpened', true, { desc: 'hide if spotify is not opened', shouldShow: p => addDependency(p.enablespotify) })
  .addInteger('spotifyMaxSongLength', 'SpotifyMaxSongLength', 100, { desc: 'in pixels, 0 for uncapped length', min: 0, shouldShow: p => addDependency(p.enablespotify) })
  .addText('spotifyPrefix', 'SpotifyPrefix', '&2Spotify &7>&r ', { shouldShow: p => addDependency(p.enablespotify) })
  .addText('spotifyFormat', 'SpotifyFormat', '&a%ARTIST% &7-&b %SONG%', { shouldShow: p => addDependency(p.enablespotify) })
  .addToggle('spotifyAlternateScrolling', 'SpotifyAlternateScrolling', false, { shouldShow: p => addDependency(p.enablespotify) })
  .addInteger('spotifyScrollSpeed', 'SpotifyScrollSpeed', 80, { min: 1, shouldShow: p => addDependency(p.enablespotify) })

  .addToggle('enablesacks', 'EnableSackTils', false, { desc: 'does things with the sacks message\nto turn on settings -> personal -> chat feedback -> sack notifs', isNewSection: true })
  .addToggle('sacksDisableMessage', 'SackTilsDisableMessage', true, { desc: 'hide the message', shouldShow: p => addDependency(p.enablesacks) })
  .addToggle('sacksDisplay', 'SackTilsDisplay', true, { desc: 'gui showing change in items', shouldShow: p => addDependency(p.enablesacks) })
  .addAction('moveSacksDisplay', 'MoveSacktilsDisplay', null, { shouldShow: p => addDependency(p.sacksDisplay) })
  .addNumber('sacksDisplayTimeout', 'SackTilsDisplayTimeout', 5000, { desc: 'how long to show changes for in ms', shouldShow: p => addDependency(p.sacksDisplay) })
  .addToggle('sacksDisplayCombineQuantities', 'SackTilsDisplayCombineQuantities', false, { desc: 'combine +16 Ender Pearl and -3 Ender Pearl into +13 Ender Pearl', shouldShow: p => addDependency(p.sacksDisplay) })
  .addToggle('sacksDisplayTrackAggregateQuantities', 'SackTilsDisplayTrackAggregateQuantities', false, { desc: 'remember previous transactions (reset on restart/reload or manually)', shouldShow: p => addDependency(p.sacksDisplay) })
  .addAction('sacksDisplayResetAggregate', 'SackTilsDisplayResetAggregate', null, { shouldShow: p => addDependency(p.sacksDisplayTrackAggregateQuantities) })
  .addText('sacksDisplayItemWhitelist', 'SackTilsDisplayItemWhitelist', '', { desc: 'case insensitive comma separated values\ndo not use quotes, they will not be parsed\nall formatting codes and non alphanumeric characters will be stripped\nwill first attempt to match by id, then strict name, then a check without spaces\nall the following will match the item "Jack o\' Lantern"\nJACK_O_LANTERN,Jack o\' Lantern,jack o lantern,jackolantern\nthe following will NOT match:\njack lantern,ack o lanter,poisonous potato', shouldShow: p => addDependency(p.sacksDisplay) })
  .addText('sacksDisplayItemBlacklist', 'SackTilsDisplayItemBlacklist', '', { desc: 'case insensitive comma separated values\ndo not use quotes, they will not be parsed\nall formatting codes and non alphanumeric characters will be stripped\nwill first attempt to match by id, then strict name, then a check without spaces\nall the following will match the item "Jack o\' Lantern"\nJACK_O_LANTERN,Jack o\' Lantern,jack o lantern,jackolantern\nthe following will NOT match:\njack lantern,ack o lanter,poisonous potato', shouldShow: p => addDependency(p.sacksDisplay) })

  .addToggle('enabledeployable', 'EnableDeployableTils', false, { isNewSection: true })
  .addOption('deployableHUD', 'DeployableHUD', 'Compact', { desc: 'show current deployable\nwhat is bubblegum?', options: ['Compact', 'Full', 'None'], shouldShow: p => addDependency(p.enabledeployable) })
  .addAction('moveDeployableHUD', 'MoveDeployableHUD', null, { shouldShow: p => addDependency(p.deployableHUD) })
  .addToggle('deployableAssumeJalapeno', 'DeployableAssumeJalapeno', true, { desc: 'assume flares have jalapeno applied\n(cannot detect programmatically because fuck hypixel)', shouldShow: p => addDependency(p.deployableHUD) })
  .addToggle('deployableHUDColorTimer', 'DeployableHUDColorTime', true, { desc: 'color the timer based on time remaining', shouldShow: p => addDependency(p.deployableHUD) })
  .addOption('deployableParticlesOwn', 'DeployableParticlesOwn', 'Default', { options: ['Default', 'None', 'Custom'], desc: 'only applies to own deployables', shouldShow: p => addDependency(p.enabledeployable) })
  .addOption('deployableParticlesOther', 'DeployableParticlesOther', 'Default', { options: ['Default', 'None', 'Custom'], shouldShow: p => addDependency(p.enabledeployable) })

  .addToggle('enableferoestimate', 'EnableFeroEstimate', false, { isNewSection: true })
  .addAction('moveFeroEstimate', 'MoveFeroEstimate', null, { shouldShow: p => addDependency(p.enableferoestimate) })
  .addInteger('feroEstimateUpdateDelay', 'FeroEstimateUpdateDelay', 500, { desc: 'delay in ms to update guess', min: 0, shouldShow: p => addDependency(p.enableferoestimate) })

  .addToggle('enablecrosshair', 'EnableCustomCrosshair', false, { isNewSection: true })
  .addOption('crosshairType', 'CustomCrosshairType', '+', { options: ['+', 'X', '/\\', 'O', '.'], shouldShow: p => addDependency(p.enablecrosshair) })
  .addColor('crosshairColor', 'CustomCrosshairColor', 0xFFFFFFFF, { shouldShow: p => addDependency(p.enablecrosshair) })
  .addToggle('crosshairInvert', 'CustomCrosshairInvertColor', false, { shouldShow: p => addDependency(p.enablecrosshair) })
  .addNumber('crosshairWidth', 'CustomCrosshairWidth', 10, { min: 0, shouldShow: p => addDependency(p.enablecrosshair) })
  .addNumber('crosshairBreadth', 'CustomCrosshairBreadth', 1, { min: 0, shouldShow: p => addDependency(p.enablecrosshair) })
  .addToggle('crosshairRenderInGui', 'CustomCrosshairRenderInGuis', false, { shouldShow: p => addDependency(p.enablecrosshair) })

  .addToggle('enablewithershieldtimer', 'EnableWitherShieldTimer', true, { isNewSection: true })
  .addAction('moveWitherShieldTimer', 'MoveWitherShieldTimer', { shouldShow: p => addDependency(p.enablewithershieldtimer) })

  .addToggle('enableneuitempreloadprogress', 'EnableNEUItemPreloaderProgressDisplay', false, { desc: 'progress indicator for neu preloading its items on launching game', isNewSection: true })
  .addAction('moveNeuItemPreloadProgress', 'MoveNEUItemPreloaderProgressDisplay', { shouldShow: p => addDependency(p.enableneuitempreloadprogress) })

  .addPage('Avarice Addons')
  .addToggle('enableavarice', 'EnableAvariceAddons', false, { desc: 'things for avarice' })

  .addToggle('avariceShowCoinCounter', 'AvariceShowCoinCounter', true, { desc: 'show avarice coins in a hud', shouldShow: p => addDependency(p.enableavarice), isNewSection: true })
  .addAction('moveAvariceCoinCounter', 'MoveAvariceCoinCounter', null, { shouldShow: p => addDependency(p.avariceShowCoinCounter) })

  .addToggle('avariceArachne', 'AvariceBigSpooderHelper', true, { desc: 'big spooder go die, i hate nons', shouldShow: p => addDependency(p.enableavarice), isNewSection: true })
  .addToggle('avariceArachneHideBroodNames', 'AvariceHideSmallSpooderNames', true, { desc: 'make small spooder names go bye', shouldShow: p => addDependency(p.avariceArachne) })
  .addToggle('avariceArachneBoxBigSpooder', 'AvariceBoxBigSpooder', true, { shouldShow: p => addDependency(p.avariceArachne) })
  .addColor('avariceArachneBoxBigSpooderColor', 'AvariceBoxBigSpooderColor', 0xEB38BBFF, { shouldShow: p => addDependency(p.avariceArachneBoxBigSpooder) })
  .addToggle('avariceArachneBoxBigSpooderEsp', 'AvariceBoxBigSpooderEsp', false, { shouldShow: p => addDependency(p.avariceArachneBoxBigSpooder) })
  .addToggle('avariceArachneBoxBigSpooderDrawArrow', 'AvariceBoxBigSpooderDrawArrow', true, { shouldShow: p => addDependency(p.avariceArachneBoxBigSpooder) })
  .addToggle('avariceArachneBoxSmallSpooders', 'AvariceBoxSmallSpooders', true, { shouldShow: p => addDependency(p.avariceArachne) })
  .addColor('avariceArachneBoxSmallSpoodersColor', 'AvariceBoxSmallSpoodersColor', 0x26ED5EFF, { shouldShow: p => addDependency(p.avariceArachneBoxSmallSpooders) })
  .addToggle('avariceArachneBoxSmallSpoodersEsp', 'AvariceBoxSmallSpoodersEsp', false, { shouldShow: p => addDependency(p.avariceArachneBoxSmallSpooders) })

  .addToggle('avariceTaraTrader', 'AvariceTaraTrader', false, { desc: 'block hits on tara if slayer quest not started\nlag go brr\nnote: doesnt block custom hits (i.e. >3 block range)\nas of writing this, xp duping is patched and trading is not possible (i.e. obsolete)', shouldShow: p => addDependency(p.enableavarice), isNewSection: true })

  .addPage('Great Spook')
  .addToggle('enablegreatspook', 'EnableGreatSpook', false, {})
  .addInteger('greatSpookPrimalCd', 'GreatSpookPrimalCd', 75, { desc: 'cd between spawns, in seconds\ncheck at hub -> tyashoi alchemist', shouldShow: p => addDependency(p.enablegreatspook) })

  .addToggle('greatSpookPrimalTimer', 'GreatSpookPrimalTimer', true, { desc: 'timer until primal fear can spawn', shouldShow: p => addDependency(p.enablegreatspook), isNewSection: true })
  .addAction('moveGreatSpookPrimalTimer', 'MoveGreatSpookPrimalTimer', null, { shouldShow: p => addDependency(p.greatSpookPrimalTimer) })
  .addToggle('greatSpookPrimalTimerHideReady', 'GreatSpookPrimalTimerHideReady', false, { desc: 'when cd is ready hide timer rather than show "READY"', shouldShow: p => addDependency(p.greatSpookPrimalTimer) })

  .addToggle('greatSpookPrimalAlert', 'GreatSpookPrimalAlert', true, { desc: 'show alert when primal is ready', shouldShow: p => addDependency(p.enablegreatspook) })
  .addInteger('greatSpookPrimalAlertTime', 'GreatSpookPrimalAlertTime', 2000, { desc: 'in ms', min: 0, shouldShow: p => addDependency(p.greatSpookPrimalAlert) })
  .addToggle('greatSpookPrimalAlertSound', 'GreatSpookPrimalAlertSound', true, { desc: 'play sound with the alert', shouldShow: p => addDependency(p.greatSpookPrimalAlert) })

  .addPage('FishingTils')
  .addToggle('enablefishingtils', 'EnableFishingTils', true, {})

  .addToggle('fishingTilsHotspotWaypoint', 'FishingTilsHotspotWaypoint', false, { shouldShow: p => addDependency(p.enablefishingtils), isNewSection: true })
  .addColor('fishingTilsHotspotWaypointColor', 'FishingTilsHotspotWaypointColor', 0xFA771EFF, { shouldShow: p => addDependency(p.fishingTilsHotspotWaypoint) })
  .addInteger('fishingTilsHotspotWaypointDisableRange', 'FishingTilsHotspotWaypointDisableRange', 10, { desc: 'disable when this many blocks (not including height) from hotspot', min: 0, shouldShow: p => addDependency(p.fishingTilsHotspotWaypoint) })
  .addToggle('fishingTilsHotspotWaypointArrow', 'FishingTilsHotspotWaypointArrow', true, { shouldShow: p => addDependency(p.fishingTilsHotspotWaypoint) })

  .addToggle('fishingTilsUpdateSBAList', 'FishingTilsUpdateSBAList', true, { desc: 'update the sba sea creature list\nrequires game restart to fully disable (why though)', shouldShow: p => addDependency(p.enablefishingtils), isNewSection: true })

  .addPage('Necromancy')
  .addToggle('enablenecromancy', 'EnableNecromancy', false, {})

  .addToggle('necromancyTrackSouls', 'NecromancyTrackSouls', true, { desc: 'track info about souls that get dropped', shouldShow: p => addDependency(p.enablenecromancy), isNewSection: true })
  .addText('necromancySoulWhitelist', 'NecromancySoulWhitelist', '', { desc: 'comma separated names, will search inclusively, case sensitive', shouldShow: p => addDependency(p.necromancyTrackSouls) })
  .addText('necromancySoulBlacklist', 'NecromancySoulBlacklist', '', { desc: 'comma separated names, will search inclusively, case sensitive', shouldShow: p => addDependency(p.necromancyTrackSouls) })
  .addToggle('necromancyAlwaysTrackBoss', 'NecromancyAlwaysTrackBoss', true, { desc: 'always track powerful (dark) souls, regardless of white/blacklist', shouldShow: p => addDependency(p.necromancyTrackSouls) })

  .addToggle('necromancySoulEsp', 'NecromancySoulEsp', false, { desc: 'esp on soul rendering', shouldShow: p => addDependency(p.necromancyTrackSouls) })
  .addToggle('necromancyShowMobName', 'NecromancyShowMobName', true, { desc: 'render name of mob above soul', shouldShow: p => addDependency(p.necromancyTrackSouls) })

  .addToggle('necromancyBoxSoul', 'NecromancyBoxSoul', true, { shouldShow: p => addDependency(p.necromancyTrackSouls) })
  .addColor('necromancySoulColorNew', 'NecromancySoulColorNew', 0x00FFFFA0, { desc: 'color of newly dropped soul', shouldShow: p => addDependency(p.necromancyBoxSoul) })
  .addColor('necromancySoulColorOld', 'NecromancySoulColorOld', 0xFF0000FF, { desc: 'color of soul about to despawn', shouldShow: p => addDependency(p.necromancyBoxSoul) })

  .addPage('Dojo')
  .addToggle('enabledojo', 'EnableDojo', false, {})

  .addToggle('dojoMastery', 'DojoMaster', true, { shouldShow: p => addDependency(p.enabledojo), isNewSection: true })
  .addToggle('dojoMasteryPointToLowest', 'DojoMasteryPointToLowest', true, { shouldShow: p => addDependency(p.dojoMastery) })
  .addColor('dojoMasteryPointToLowestColor', 'DojoMasteryPointToLowestColor', 0x55FF55FF, { shouldShow: p => addDependency(p.dojoMasteryPointToLowest) })
  .addToggle('dojoMasteryShowLowestTime', 'DojoMasteryShowLowestTime', true, { desc: 'render lowest time below crosshair', shouldShow: p => addDependency(p.dojoMastery) })
  .addToggle('dojoMasteryPointToNext', 'DojoMasteryPointToNext', true, { shouldShow: p => addDependency(p.dojoMastery) })
  .addColor('dojoMasteryPointToNextColor', 'DojoMasteryPointToNextColor', 0x5555FFFF, { shouldShow: p => addDependency(p.dojoMasteryPointToNext) })
  .addToggle('dojoMasteryPointToNextTimer', 'DojoMasteryPointToNextTimer', true, { desc: 'show timer for the next block', shouldShow: p => addDependency(p.dojoMastery) })
  .addToggle('dojoMasteryHideTitles', 'DojoMasteryHideTitles', true, { shouldShow: p => addDependency(p.dojoMastery) })

  .addPage('Entity Reducer')
  .addToggle('enableentityreducer', 'EnableEntityReducer', false, { desc: 'reduce strain from excess entity spam\n"hiding" the entity prevents them from rendering, but you can still interact with them\n"removing" the entity completely deletes them\nremoving is better for performance but to get them back you must reload them from the server' })

  .addToggle('entityReducerHub', 'ReduceHubEntities', true, { isNewSection: true, shouldShow: p => addDependency(p.enableentityreducer) })
  .addOption('entityReducerHubMap', 'ReduceHubMap', 'Remove', { desc: 'map of skyblock @ hub', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubCityProject', 'ReduceHubCityProject', 'Remove', { options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubTopAuctions', 'ReduceHubTopAuctions', 'Remove', { desc: 'top listings on AH, under auction house (only the cases not the items)', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubHex', 'ReduceHubHex', 'Remove', { desc: 'physical hex pedestal', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubDHub', 'ReduceHubCatacombs', 'Remove', { desc: 'the catacombs entrance near crypts', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubJax', 'ReduceHubJax', 'Remove', { desc: 'random bows, arrows ,swords, etc near jax/rosetta', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubKatHouse', 'ReduceHubKatHouse', 'Remove', { desc: 'pet care area on 2nd floor of kat house', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubVincent', 'ReduceHubVincent', 'Remove', { desc: 'paintings in vincent house', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubTaylor', 'ReduceHubTaylor', 'Remove', { desc: 'armor in basement of taylor house', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubCarpenter', 'ReduceHubCarpenter', 'Remove', { desc: 'carpentry objects', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubMarco', 'ReduceHubMarco', 'Remove', { desc: 'paintings in marco house', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })
  .addOption('entityReducerHubRabbit', 'ReduceHubRabbitFamily', 'Remove', { desc: 'rabbit house residents', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerHub) })

  .addToggle('entityReducerDHub', 'ReduceDungeonHubEntities', true, { isNewSection: true, shouldShow: p => addDependency(p.enableentityreducer) })
  .addOption('entityReducerDHubRace', 'ReduceDHubRaceLeaderboard', 'Remove', { desc: 'leaderboard for races', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerDHub) })

  .addToggle('entityReducerMines', 'ReduceDwarvenMinesEntities', true, { isNewSection: true, shouldShow: p => addDependency(p.enableentityreducer) })
  .addOption('entityReducerMinesFossil', 'ReduceDwarvenFossilCenter', 'Remove', { desc: 'fossil research center in tunnels', options: ['Normal', 'Hide', 'Remove'], shouldShow: p => addDependency(p.entityReducerMines) })

  .addPage('Testing')
  .addToggle('enableboxallentities', 'EnableBoxAllEntities', false, { desc: 'mostly for debugging' })
  .addToggle('boxAllEntitiesInvis', 'BoxAllEntitiesInvisible', false, { desc: 'box invisible entities', shouldShow: p => addDependency(p.enableboxallentities) })
  .addColor('boxAllEntitiesColor', 'BoxAllEntitiesColor', 0xFF0000FF, { shouldShow: p => addDependency(p.enableboxallentities) })
  .addToggle('boxAllEntitiesEsp', 'BoxAllEntitiesEsp', true, { shouldShow: p => addDependency(p.enableboxallentities) })
  .addToggle('boxAllEntitiesName', 'BoxAllEntitiesName', false, { desc: 'show nametag', shouldShow: p => addDependency(p.enableboxallentities) })
  .addToggle('boxAllEntitiesClassName', 'BoxAllEntitiesClassName', false, { desc: 'show class name', shouldShow: p => addDependency(p.enableboxallentities) })
  .addText('boxAllEntitiesWhitelist', 'BoxAllEntitiesWhitelist', '', { desc: 'comma separated class names', shouldShow: p => addDependency(p.enableboxallentities) })
  .addText('boxAllEntitiesBlacklist', 'BoxAllEntitiesBlacklist', '', { desc: 'comma separated class names', shouldShow: p => addDependency(p.enableboxallentities) })
  .addToggle('boxAllEntitiesEntityId', 'BoxAllEntitiesEntityId', false, { desc: 'show entity id', shouldShow: p => addDependency(p.enableboxallentities) })

  .addToggle('enablelogdamage', 'EnableLogDamage', false, { desc: 'log damage numbers in chat', isNewSection: true })
  .addNumber('logDamageRange', 'LogDamageRange', 5, { desc: 'ignore damage numbers outside this range\nin blocks', min: 0, shouldShow: p => addDependency(p.enablelogdamage) })
  .addInteger('logDamageThreshold', 'LogDamageThreshold', 0, { desc: 'only log damage when above this amount\n0 to disable', min: 0, shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageNormal', 'LogDamageNormal', true, { desc: 'non crit', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageCrit', 'LogDamageCrit', true, { desc: 'crit', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageWither', 'LogDamageWither', true, { desc: 'withering effect', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageVenomous', 'LogDamageVenomous', true, { desc: 'venomous/toxic poison', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageSuffocation', 'LogDamageSuffocation', true, { desc: 'suffocation/drowning', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageFire', 'LogDamageFire', true, { desc: 'fire/fa/flame', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageLightning', 'LogDamageLightning', true, { desc: 'thunderlord/thunderbolt', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamagePet', 'LogDamagePet', true, { desc: 'pet e.g. snowman', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageOverload', 'LogDamageOverload', true, { desc: 'overload', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageExtremeFocus', 'LogDamageExtremeFocus', true, { desc: 'extreme focus (endstone sword)', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageOctodexterity', 'LogDamageOctodexterity', true, { desc: 'octodexterity (tara full set)', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageWitherSkull', 'LogDamageWitherSkull', true, { desc: 'withermancer/withers', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageLove', 'LogDamageLove', true, { desc: 'ring of love etc. proc', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageCurse', 'LogDamageCurse', true, { desc: 'gaia construct lightning', shouldShow: p => addDependency(p.enablelogdamage) })
  .addToggle('logDamageCombo', 'LogDamageCombo', true, { desc: 'blaze dagger repeat', shouldShow: p => addDependency(p.enablelogdamage) })

  .addToggle('enableshowserverlocation', 'EnableShowServerLocation', false, { desc: 'render where the last reported position to the server is', isNewSection: true })
  .addColor('showServerLocationColor', 'ShowServerLocationColor', 0x808080FF, { shouldShow: p => addDependency(p.enableshowserverlocation) })
  .addColor('showServerLookColor', 'ShowServerLookColor', 0x6D2B2BFF, { shouldShow: p => addDependency(p.enableshowserverlocation) })

  .addToggle('enablelogpackets', 'EnablePacketLogger', false, { desc: 'logs packets to file', isNewSection: true })
  .addToggle('logPacketClient', 'PacketLoggerClientPackets', true, { desc: 'log client -> server packets', shouldShow: p => addDependency(p.enablelogpackets) })
  .addToggle('logPacketServer', 'PacketLoggerServerPackets', true, { desc: 'log server -> client packets', shouldShow: p => addDependency(p.enablelogpackets) })
  .addText('logPacketWhitelist', 'PacketLoggerWhitelist', '', { desc: 'comma separated class names, e.g. S02PacketChat', shouldShow: p => addDependency(p.enablelogpackets) })
  .addText('logPacketBlacklist', 'PacketLoggerBlacklist', '', { desc: 'comma separated class names, e.g. S02PacketChat', shouldShow: p => addDependency(p.enablelogpackets) })
  .addAction('logPacketEnablePresetC1', 'PacketLoggerEnableClientNetwork', { desc: 'C00PacketKeepAlive\nC15PacketClientSettings\nC16PacketClientStatus\nC17PacketCustomPayload', shouldShow: p => addDependency(p.logPacketClient) })
  .addAction('logPacketEnablePresetC2', 'PacketLoggerEnableClientAction', { desc: 'C01PacketChatMessage\nC02PacketUseEntity\nC07PacketPlayerDigging\nC08PacketPlayerBlockPlacement\nC09PacketHeldItemChange\nC0APacketAnimation\nC0BPacketEntityAction\nC0DPacketCloseWindow\nC0EPacketClickWindow\nC14PacketTabComplete', shouldShow: p => addDependency(p.logPacketClient) })
  .addAction('logPacketEnablePresetC3', 'PacketLoggerEnableClientMovement', { desc: 'C03PacketPlayer\nC04PacketPlayerPosition\nC05PacketPlayerLook\nC06PacketPlayerPosLook\nC0CPacketInput\nC13PacketPlayerAbilities', shouldShow: p => addDependency(p.logPacketClient) })
  .addAction('logPacketEnablePresetC4', 'PacketLoggerEnableClientInventory', { desc: 'C0FPacketConfirmTransaction\nC10PacketCreativeInventoryAction\nC11PacketEnchantItem\nC12PacketUpdateSign', shouldShow: p => addDependency(p.logPacketClient) })
  .addAction('logPacketEnablePresetS1', 'PacketLoggerEnableServerNetwork', { desc: 'S00PacketKeepAlive\nS03PacketTimeUpdate\nS37PacketStatistics\nS3FPacketCustomPayload\nS40PacketDisconnect\nS46PacketSetCompressionLevel\nS48PacketResourcePackSend', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS2', 'PacketLoggerEnableServerWorldSetup', { desc: 'S01PacketJoinGame\nS05PacketSpawnPosition\nS07PacketRespawn\nS41PacketServerDifficulty\nS44PacketWorldBorder', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS3', 'PacketLoggerEnableServerPlayerMovement', { desc: 'S08PacketPlayerPosLook\nS39PacketPlayerAbilities', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS4', 'PacketLoggerEnableServerPlayerState', { desc: 'S06PacketUpdateHealth\nS1FPacketSetExperience\nS2BPacketChangeGameState\nS3APacketTabComplete\nS43PacketCamera', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS5', 'PacketLoggerEnableServerInfo', { desc: 'S02PacketChat\nS32PacketConfirmTransaction\nS38PacketPlayerListItem\nS3BPacketScoreboardObjective\nS3CPacketUpdateScore\nS3DPacketDisplayScoreboard\nS3EPacketTeams\nS45PacketTitle\nS47PacketPlayerListHeaderFooter', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS6', 'PacketLoggerEnableServerEntityInfo', { desc: 'S04PacketEntityEquipment\nS0CPacketSpawnPlayer\nS0EPacketSpawnObject\nS0FPacketSpawnMob\nS10PacketSpawnPainting\nS11PacketSpawnExperienceOrb\nS13PacketDestroyEntities\nS1BPacketEntityAttach\nS1CPacketEntityMetadata\nS1DPacketEntityEffect\nS1EPacketRemoveEntityEffect\nS20PacketEntityProperties\nS2CPacketSpawnGlobalEntity\nS35PacketUpdateTileEntity\nS42PacketCombatEvent\nS49PacketUpdateEntityNBT', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS7', 'PacketLoggerEnableServerEntityMovement', { desc: 'S08PacketPlayerPosLook\nS12PacketEntityVelocity\nS14PacketEntity\nS15PacketEntityRelMove\nS16PacketEntityLook\nS17PacketEntityLookMove\nS18PacketEntityTeleport\nS19PacketEntityHeadLook', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS8', 'PacketLoggerEnableServerEntityAction', { desc: 'S09PacketHeldItemChange\nS0APacketUseBed\nS0BPacketAnimation\nS0DPacketCollectItem\nS19PacketEntityStatus', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS9', 'PacketLoggerEnableServerWorldUpdate', { desc: 'S21PacketChunkData\nS22PacketMultiBlockChange\nS23PacketBlockChange\nS24PacketBlockAction\nS25PacketBlockBreakAnim\nS26PacketMapChunkBulk\nS33PacketUpdateSign\nS35PacketUpdateTileEntity\nS44PacketWorldBorder', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS10', 'PacketLoggerEnableServerExtras', { desc: 'S27PacketExplosion\nS28PacketEffect\nS29PacketSoundEffect\nS2APacketParticles', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS11', 'PacketLoggerEnableServerInventory', { desc: 'S2DPacketOpenWindow\nS2EPacketCloseWindow\nS2FPacketSetSlot\nS30PacketWindowItems\nS31PacketWindowProperty\nS32PacketConfirmTransaction\nS36PacketSignEditorOpen', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketEnablePresetS12', 'PacketLoggerEnableServerMap', { desc: 'S34PacketMaps', shouldShow: p => addDependency(p.logPacketServer) })
  .addAction('logPacketClearWhitelist', 'PacketLoggerClearWhitelist', { shouldShow: p => addDependency(p.enablelogpackets) })

  .addPage('Misc.')
  .addToggle('enableexcavatorsolver', 'EnableExcavatorSolver', false, { desc: 'find fossils' })
  .addToggle('excavatorSolverOnlyShowBest', 'ExcavatorSolverOnlyHighlightBest', true, { desc: 'only highlight the best move', shouldShow: p => addDependency(p.enableexcavatorsolver) })
  .addToggle('excavatorSolverShowRoute', 'ExcavatorSolverHighlightStartPath', false, { desc: 'highlight best starting path (turn off if citrine gemstones)', shouldShow: p => addDependency(p.enableexcavatorsolver) })
  .addOption('excavatorSolverDirtTooltip', 'ExcavatorSolverDirtTooltip', 'Custom', { options: ['Default', 'Hide', 'Custom'], shouldShow: p => addDependency(p.enableexcavatorsolver) })
  .addOption('excavatorSolverDustTooltip', 'ExcavatorSolverDustTooltip', 'Custom', { options: ['Default', 'Hide', 'Custom'], shouldShow: p => addDependency(p.enableexcavatorsolver) })
  .addToggle('excavatorSolverAutoClose', 'ExcavatorSolverAutoClose', false, { desc: 'automatically close excavator when all clicks used', shouldShow: p => addDependency(p.enableexcavatorsolver) })

  .addToggle('enablebettergfs', 'EnableBetterGFS', false, { desc: 'autocomplete for gfs, and shorthand\ne.g. /gfs w c 1 -> /gfs WITHER_CATALYST 1', isNewSection: true })
  .addOption('betterGFSIDPref', 'BetterGFSIdPreference', 'ID', { desc: 'which format to prefer (name vs id)\nName: replace with qualified name, ID: coerce to ID\nDynamic: use whatever format was given (in theory) it is broken af so it is disabled :)', options: ['ID', 'Name'], shouldShow: p => addDependency(p.enablebettergfs) })
  .addInteger('betterGFSBlankAmount', 'BetterGFSUnspecifiedAmount', 1, { desc: 'amount to default to when not provided\ne.g. /gfs w c -> /gfs WITHER_CATALYST <insert amount>', min: 1, max: 2240, shouldShow: p => addDependency(p.enablebettergfs) })

  .addToggle('enablecpv', 'EnableChickTilsPV', true, { desc: '/cpv, neu /pv wrapper but with different api\n(almost 100% success rate!)', isNewSection: true })
  .addToggle('cpvReplaceNeu', 'ChickTilsPVReplaceNEU', false, { desc: 'replace /pv command (may require restart when disabling)', shouldShow: p => addDependency(p.enablecpv) })
  .addToggle('cpvAutoCompleteTabList', 'ChickTilsPVAutoCompleteTabList', true, { desc: 'autocomplete /pv with names from tab list', shouldShow: p => addDependency(p.enablecpv) })
  .addToggle('cpvAutoCompleteParty', 'ChickTilsPVAutoCompleteParty', true, { desc: 'autcomplete /pv with party members', shouldShow: p => addDependency(p.enablecpv) })

  .addToggle('enableclipboard', 'EnableClipboardThing', true, { desc: '/clipboard\nset, get, list, and remove\n/cbs and /cbg and /cbl and /cbr\n/clipboard set <name> | /cbg <name> | /clipboard list | /cbr <name>', isNewSection: true })

  .addToggle('enablevision', 'DisableBlindness', true, { desc: 'disable blindness', isNewSection: true })

  .addToggle('enablecake', 'EnableCakeHelper', true, { desc: 'i like eat cake.', isNewSection: true })

  .addToggle('enableunfocus', 'PreventRenderingWhenUnfocused', false, { desc: 'similar to patcher\'s unfocused fps\nbut instead of capping fps, it completely stops rendering', isNewSection: true })

  .addToggle('enableassfangcheese', 'EnableAssfangCheeseHealth', false, { desc: 'show real assfang health\nobsolete', isNewSection: true })
  .addAction('moveAssfangCheese', 'MoveAssfangCheeseHealth', null, { shouldShow: p => addDependency(p.enableassfangcheese) })

  .addToggle('enableblockhighlight', 'EnableBlockHighlight', false, { isNewSection: true })
  .addToggle('blockHighlightBoxEntity', 'BlockHighlightBoxEntity', false, { desc: 'box the entity you are looking at', shouldShow: p => addDependency(p.enableblockhighlight) })
  .addColor('blockHighlightWireColor', 'BlockHighlightWireColor', 0x00000066, { shouldShow: p => addDependency(p.enableblockhighlight) })
  .addColor('blockHighlightFillColor', 'BlockHighlightFillColor', 0x00000000, { shouldShow: p => addDependency(p.enableblockhighlight) })
  .addNumber('blockHighlightWireWidth', 'BlockHighlightWireWidth', 2, { min: 0, shouldShow: p => addDependency(p.enableblockhighlight) })
  .addToggle('blockHighlightCheckEther', 'BlockHighlightCheckEther', true, { shouldShow: p => addDependency(p.enableblockhighlight) })
  .addToggle('blockHighlightEtherCheeto', 'BlockHighlightEtherCheeto', false, { desc: 'whether to not hide ether overlay when looking at an interactable block (e.g. hopper)', shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addColor('blockHighlightEtherWireColor', 'BlockHighlightEtherWireColor', 0x2EDD17A0, { shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addColor('blockHighlightEtherFillColor', 'BlockHighlightEtherFillColor', 0x60DE5560, { shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addNumber('blockHighlightEtherWireWidth', 'BlockHighlightEtherWireWidth', 3, { min: 0, shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addColor('blockHighlightCantEtherWireColor', 'BlockHighlightCantEtherWireColor', 0xCA2207A0, { shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addColor('blockHighlightCantEtherFillColor', 'BlockHighlightCantEtherFillColor', 0xBA2B1E60, { shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addNumber('blockHighlightCantEtherWireWidth', 'BlockHighlightCantEtherWireWidth', 3, { min: 0, shouldShow: p => addDependency(p.blockHighlightCheckEther) })
  .addToggle('blockHighlightCantEtherShowReason', 'BlockHighlightCantEtherShowReason', true, { shouldShow: p => addDependency(p.blockHighlightCheckEther) })

  .addToggle('enablehidedivanparticles', 'HideDivanCoatingParticles', true, { desc: 'only hides your own', isNewSection: true })

  .addToggle('enablesbaenchant', 'UpdateSBAEnchantList', true, { desc: 'need to rs game to unload properly (why would you?)', isNewSection: true })

  .addToggle('enablepearlpath', 'EnablePearlPath', false, { isNewSection: true })
  .addToggle('pearlPathEsp', 'PearlPathEsp', false, { shouldShow: p => addDependency(p.enablepearlpath) })
  .addColor('pearlPathPathColor', 'PearlPathColor', 0xFF0000FF, { desc: 'color of path of pearl', shouldShow: p => addDependency(p.enablepearlpath) })
  .addColor('pearlPathDestColorOutline', 'PearlPathDestinationColorOutline', 0x0000FFFF, { desc: 'outline color of player hitbox on teleport', shouldShow: p => addDependency(p.enablepearlpath) })
  .addColor('pearlPathDestColorFill', 'PearlPathDestinationColorFill', 0x00000000, { desc: 'fill color of player hitbox on teleport', shouldShow: p => addDependency(p.enablepearlpath) })
  .addToggle('pearlPathCollideEntity', 'PearlPathCollideWithEntities', false, { desc: 'whether to check for collisions with entities', shouldShow: p => addDependency(p.enablepearlpath) })
  .addColor('pearlPathCollidedEntityColor', 'PearlPathCollidedEntityColor', 0x00FF00FF, { desc: 'color to box entity that was collided with', shouldShow: p => addDependency(p.enablepearlpath) })
  .addToggle('pearlPathCheeto', 'PearlPathCheeto', false, { desc: 'shame shame shame\ndoesn\'t disable when looking at a block', shouldShow: p => addDependency(p.enablepearlpath) })

  .addToggle('enablelookat', 'EnableLookAt', true, { desc: '/lookat <pitch> <yaw>\ndisplays a thing to help aim', isNewSection: true })
  .addColor('lookAtColor', 'LookAtColor', 0x00FFFFFF, { shouldShow: p => addDependency(p.enablelookat) })
  .addNumber('lookAtSize', 'LookAtSize', 0.01, { min: 0, shouldShow: p => addDependency(p.enablelookat) })
  .addToggle('lookAtPointTo', 'LookAtPointToLocation', false, { shouldShow: p => addDependency(p.enablelookat) })
  .addNumber('lookAtThreshold', 'LookAtTreshold', 0.1, { min: 0, desc: 'threshold (in degrees) until it is "good enough"', shouldShow: p => addDependency(p.enablelookat) })
  .addInteger('lookAtTimeout', 'LookAtTimeout', 600, { min: 1, desc: 'time (in ticks) until it gives up', shouldShow: p => addDependency(p.enablelookat) })

  .addToggle('enabledarkmonolith', 'EnableDarkMonolith', false, { isNewSection: true })
  .addInteger('darkMonolithScanDelay', 'DarkMonolithScanDelay', 5, { desc: 'time in ticks taken to scan all possible positions, lower = laggier', min: 1, shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addToggle('darkMonolithEsp', 'DarkMonolithEsp', true, { shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addColor('darkMonolithColor', 'DarkMonolithColor', 0x000000FF, { shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addColor('darkMonolithPossibleColor', 'DarkMonolithPossibleColor', 0x55FF55FF, { shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addColor('darkMonolithScannedColor', 'DarkMonolithScannedColor', 0xFF5555FF, { shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addToggle('darkMonolithPointTo', 'DarkMonolithPointTo', true, { shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addToggle('darkMonolithTrackDrops', 'DarkMonolithTrackDrops', true, { shouldShow: p => addDependency(p.enabledarkmonolith) })
  .addAction('moveDarkMonolithDropsTracker', 'MoveDarkMonolithDropsTracker', null, { shouldShow: p => addDependency(p.darkMonolithTrackDrops) })
  .addAction('resetDarkMonolithDropsTracker', 'ResetDarkMonolithDropsTracker', null, { shouldShow: p => addDependency(p.darkMonolithTrackDrops) })

  .addToggle('enablevoidgloomarmorstandfix', 'EnableVoidgloomArmorStandFix', true, { desc: 'fixes hypixel not deleting armor stands', isNewSection: true })

  .collapse();

const settings = builder.build();
export default settings;
export const props = builder.props;